id: P6C869751
initial_creation_type: input
source_metadata:
  title: Āptamīmāṃsā
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy
  data entry: Diwakar Acharya
  contribution to GRETIL: Diwakar Acharya
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:27:08.623053'
last_modified_at: '2022-03-09T15:27:08.623071'
